<?php

/**
 * Builder shortcode icon list
 *
 * @package flatsome
 */

return array(
    ''                     => 'None',
    'icon-arrow-down'      => 'Arrow Down',
    'icon-arrow-left'      => 'Arrow Left',
    'icon-arrow-right'     => 'Arrow Right',
    'icon-arrow-up'        => 'Arrow Up',
    'icon-send'        => 'Send',
    'icon-send-horizontal'        => 'Send Horizontal',
    'icon-flame'        => 'Flame',
    'icon-timer'            => 'Timer',
    'icon-folders'            => 'Folders',
    'icon-circle-check'            => 'Circle Check',
    'icon-circle-play'            => 'Play',
    'icon-clock'           => 'Clock',
    'icon-cross'           => 'Cross',
    'icon-discord'         => 'Discord',
    'icon-dribbble'        => 'Dribbble',
    'icon-envelop'         => 'Envelope',
    'icon-expand'          => 'Expand',
    'icon-facebook'        => 'Facebook',
    'icon-feed'            => 'Feed',
    'icon-flickr'          => 'Flickr',
    'icon-gift'            => 'Gift',
    'icon-google-plus'     => 'Google Plus',
    'icon-heart'           => 'Heart',
    'icon-heart-o'         => 'Heart Outline',
    'icon-instagram'       => 'Instagram',
    'icon-linkedin'        => 'linkedIn',
    'icon-lock'            => 'Lock',
    'icon-map-pin-fill'    => 'Map Pin',
    'icon-menu'            => 'Menu',
    'icon-pen-alt-fill'    => 'Pen',
    'icon-phone'           => 'Phone',
    'icon-pinterest'       => 'Pinterest',
    'icon-plus'            => 'Plus',
    'icon-search'          => 'Search',
    'icon-shopping-bag'    => 'Shopping Bag',
    'icon-shopping-basket' => 'Shopping Basket',
    'icon-shopping-cart'   => 'Shopping Cart',
    'icon-skype'           => 'Skype',
    'icon-snapchat'        => 'SnapChat',
    'icon-star'            => 'Star',
    'icon-star-o'          => 'Star Outline',
    'icon-tag'             => 'Tag',
    'icon-telegram'        => 'Telegram',
    'icon-threads'         => 'Threads',
    'icon-tiktok'          => 'TikTok',
    'icon-tumblr'          => 'Tumblr',
    'icon-twitch'          => 'Twitch',
    'icon-twitter'         => 'Twitter',
    'icon-user'            => 'User',
    'icon-user-o'          => 'User Outline',
    'icon-vk'              => 'VKontakte',
    'icon-whatsapp'        => 'WhatsApp',
    'icon-x'               => 'X (social media)',
    'icon-youtube'         => 'Youtube',
);
